<a href="https://colab.research.google.com/github/Manish-248/numpy__analysis.ipynb/blob/main/numpy_fundamentals_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📊 NumPy: Arrays, Matrices, and Operations

## 🎯 Objective
This notebook demonstrates fundamental and advanced NumPy operations, including:
- Array creation and transformation
- Indexing and slicing
- Reshaping and axis manipulation
- Vectorized computations

## 🛠️ Libraries Used
- NumPy

## 📌 Why NumPy?
NumPy provides efficient numerical computation using:
- Optimized C-based operations
- Vectorization (faster than loops)
- Memory-efficient data structures

## ⚙️ Environment Setup

We begin by importing NumPy and setting a random seed for reproducibility.

In [216]:
import numpy as np

# Ensures same random results every run
np.random.seed(42)

## 📦 Array Creation

NumPy arrays (ndarrays) are the core data structure.

### Key Points:
- Arrays must contain elements of the same data type
- Lists are automatically converted if possible
- Arrays can be 1D, 2D, or higher dimensional

In [217]:
# 1D Array
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)

print("1D Array:")
print(arr1)


# 2D Array
data2 = [range(1, 5), range(5, 9)]
arr2 = np.array(data2)

print("\n2D Array:")
print(arr2)


# Convert back to list
print("\nConverted back to list:")
print(arr2.tolist())

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3 4]
 [5 6 7 8]]

Converted back to list:
[[1, 2, 3, 4], [5, 6, 7, 8]]


### 🔍 Insight:
- NumPy arrays are more efficient than Python lists
- They support vectorized operations
- Conversion between list ↔ array is seamless

## ✨ Special Array Creation

NumPy provides built-in functions to generate arrays quickly.

In [218]:
print("Zeros (1D):")
print(np.zeros(5))

print("\nZeros (2D):")
print(np.zeros((3, 3)))

print("\nOnes:")
print(np.ones(5))

print("\nLinspace (0 → 1, 5 points):")
print(np.linspace(0, 1, 5))

print("\nLogspace (10^0 → 10^3):")
print(np.logspace(0, 3, 4))

print("\nArange:")
print(np.arange(5))

Zeros (1D):
[0. 0. 0. 0. 0.]

Zeros (2D):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones:
[1. 1. 1. 1. 1.]

Linspace (0 → 1, 5 points):
[0.   0.25 0.5  0.75 1.  ]

Logspace (10^0 → 10^3):
[   1.   10.  100. 1000.]

Arange:
[0 1 2 3 4]


### 🔍 Insight:
- `zeros()` and `ones()` are useful for initialization
- `linspace()` is used in plotting and simulations
- `logspace()` is useful in exponential scaling problems
- `arange()` is NumPy’s version of Python’s `range()`

## 🔍 Array Inspection

Understanding array structure is critical for data manipulation.

In [219]:
print("Data type:", arr1.dtype)
print("Number of dimensions:", arr2.ndim)
print("Shape (rows, columns):", arr2.shape)
print("Total elements:", arr2.size)
print("Length (rows):", len(arr2))

Data type: int64
Number of dimensions: 2
Shape (rows, columns): (2, 4)
Total elements: 8
Length (rows): 2


### 🔍 Insight:
- `dtype` → type of elements (int, float, etc.)
- `ndim` → number of dimensions
- `shape` → structure of array
- `size` → total number of elements
- `len()` → size along first axis (rows)

## 🔄 Reshaping and Axis Manipulation

Reshaping allows us to change the structure of an array without changing its data.

### Key Concepts:
- Total number of elements must remain constant
- Shape defines dimensions: (rows, columns)
- Axis defines direction:
  - Axis 0 → rows
  - Axis 1 → columns

Understanding axes is critical for data manipulation and machine learning workflows.

In [220]:
# Create array
arr = np.arange(10, dtype=float)

print("Original Array:")
print(arr)

# Reshape into 2 rows and 5 columns
arr_2d = arr.reshape((2, 5))

print("\nReshaped (2x5):")
print(arr_2d)
print("Shape:", arr_2d.shape)

# Reshape into 5 rows and 2 columns
arr_reshaped = arr_2d.reshape((5, 2))

print("\nReshaped (5x2):")
print(arr_reshaped)

Original Array:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

Reshaped (2x5):
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
Shape: (2, 5)

Reshaped (5x2):
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


### 🔍 Insight:
- Reshaping does not change the data, only its structure
- Incorrect reshape (wrong size) will raise an error
- Always ensure total elements match:
  10 elements → (2×5) or (5×2), not (3×3)

## 📐 Understanding Axis (Very Important)

Axis represents the dimension along which operations are performed.

For a 2D array:
- Axis 0 → vertical direction (down rows)
- Axis 1 → horizontal direction (across columns)

Think:
👉 Axis 0 = "down"
👉 Axis 1 = "across"

In [221]:
arr = np.arange(10).reshape(2, 5)

print("Array:\n", arr)

# Sum across rows (axis=1)
print("\nSum across rows (axis=1):")
print(arr.sum(axis=1))

# Sum across columns (axis=0)
print("\nSum across columns (axis=0):")
print(arr.sum(axis=0))

Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Sum across rows (axis=1):
[10 35]

Sum across columns (axis=0):
[ 5  7  9 11 13]


### 🔍 Insight:
- axis=0 → collapse rows → gives column-wise results
- axis=1 → collapse columns → gives row-wise results
- Axis confusion is one of the most common beginner mistakes

## ➕ Adding a New Axis

Sometimes we need to convert a 1D array into:
- Column vector
- Row vector

This is essential in machine learning and matrix operations.

In [222]:
a = np.array([0, 1])

print("Original Array:")
print(a)
print("Shape:", a.shape)

# Convert to column vector
a_col = a[:, np.newaxis]

print("\nColumn Vector:")
print(a_col)
print("Shape:", a_col.shape)

# Alternative syntax
a_col_alt = a[:, None]

print("\nAlternative Column Vector:")
print(a_col_alt)

Original Array:
[0 1]
Shape: (2,)

Column Vector:
[[0]
 [1]]
Shape: (2, 1)

Alternative Column Vector:
[[0]
 [1]]


### 🔍 Insight:
- Original shape: (2,)
- Column vector: (2,1)
- Adding axis changes dimensionality → critical for matrix multiplication

## 🔁 Transpose

Transpose swaps rows and columns.

In [223]:
print("Column Vector:\n", a_col)

print("\nTranspose (Row Vector):")
print(a_col.T)

Column Vector:
 [[0]
 [1]]

Transpose (Row Vector):
[[0 1]]


### 🔍 Insight:
- Transpose converts:
  (n,1) → (1,n)
- Used in linear algebra and ML models

## 🔥 Flatten vs Ravel (Copy vs View)

Flattening converts multi-dimensional arrays into 1D arrays.

### Two Methods:
- flatten() → returns a COPY
- ravel() → returns a VIEW (if possible)

This distinction is critical for memory and performance.

In [224]:
arr = np.arange(10).reshape(2, 5)

flat = arr.flatten()

# Modify flattened array
flat[0] = 99

print("Flattened Array:")
print(flat)

print("\nOriginal Array (unchanged):")
print(arr)

Flattened Array:
[99  1  2  3  4  5  6  7  8  9]

Original Array (unchanged):
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [225]:
arr = np.arange(10).reshape(2, 5)

ravel = arr.ravel()

# Modify ravel array
ravel[0] = 99

print("Ravel Array:")
print(ravel)

print("\nOriginal Array (modified):")
print(arr)

Ravel Array:
[99  1  2  3  4  5  6  7  8  9]

Original Array (modified):
[[99  1  2  3  4]
 [ 5  6  7  8  9]]


### 🔍 Insight:
- flatten() → creates new memory → safe but slower
- ravel() → shares memory → faster but risky

👉 If you modify ravel → original array changes  
👉 If you modify flatten → original array stays same  

This concept is frequently asked in interviews.

## 🧠 Memory Behavior (Advanced Concept)

NumPy tries to avoid copying data to improve performance.

- View → shares memory
- Copy → independent memory

Why this matters:
- Faster computations
- Lower memory usage
- But can cause unintended side effects

## 🧠 NumPy Memory Model (Row-Major Order)

NumPy stores arrays in **row-major order (C-style)**.

### What does this mean?

For a 2D array:
- Data is stored row by row
- Axis 0 → rows
- Axis 1 → columns

For a 3D array:
- Axis 0 → "planes" (depth)
- Axis 1 → rows
- Axis 2 → columns

### Why this matters:
- Faster computation
- Efficient memory access
- Important for reshaping & slicing

## 🧪 Demonstration of Row-Major Order

In [226]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original Array:\n", arr)

# Flatten the array
flat = arr.flatten()

print("\nFlattened Array:", flat)

Original Array:
 [[1 2 3]
 [4 5 6]]

Flattened Array: [1 2 3 4 5 6]


### 🔍 Insight:
Flattened output → [1, 2, 3, 4, 5, 6]

👉 This proves:
NumPy stores elements **row by row**

## 🔬 Check Memory Order Explicitly

In [227]:
print("Is C-contiguous (row-major)?", arr.flags['C_CONTIGUOUS'])
print("Is F-contiguous (column-major)?", arr.flags['F_CONTIGUOUS'])

Is C-contiguous (row-major)? True
Is F-contiguous (column-major)? False


### 🔍 Output:
C_CONTIGUOUS → True  
F_CONTIGUOUS → False  

👉 Confirms NumPy uses row-major storage

In [228]:
# Column-major flatten
flat_F = arr.flatten(order='F')

print("Row-major flatten:", arr.flatten())
print("Column-major flatten:", flat_F)

Row-major flatten: [1 2 3 4 5 6]
Column-major flatten: [1 4 2 5 3 6]


### 🔍 Difference:

Row-major → [1, 2, 3, 4, 5, 6]  
Column-major → [1, 4, 2, 5, 3, 6]

👉 This shows how memory traversal changes

## 🎯 Real-World Importance

- Impacts performance in large datasets
- Important for reshaping operations
- Critical in deep learning (NumPy, PyTorch, TensorFlow)

## ⚡ Vectorized Operations in NumPy

Vectorization refers to performing operations on entire arrays **without using explicit Python loops**.

### Why is this powerful?

- Faster execution (runs in optimized C code)
- Cleaner and more readable code
- Less error-prone

👉 This is one of the **biggest advantages of NumPy**

## 🧪 Basic Vectorized Computations

In [229]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Multiply entire array
print(arr * 10)

# Square root
print(np.sqrt(arr))

# Power
print(arr ** 2)

[10 20 30 40 50]
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 1  4  9 16 25]


### 🔍 Insight:
- Operations apply **element-wise**
- No loops needed
- Extremely fast compared to Python loops

## 🔢 Element-wise Array Operations

In [230]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


### 🔍 Insight:
Each element in `a` is operated with corresponding element in `b`

👉 This is NOT matrix multiplication — it's element-wise

## 📊 NumPy Universal Functions (ufuncs)

In [231]:
arr = np.array([1, 4, 9, 16])

print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Log:", np.log(arr))

Square root: [1. 2. 3. 4.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Log: [0.         1.38629436 2.19722458 2.77258872]


### 🔍 Common ufuncs:
- np.sqrt()
- np.exp()
- np.log()
- np.sin(), np.cos()

👉 These are optimized and very fast

## 📏 Statistical Functions

In [232]:
data = np.random.randn(4, 3)

print("Array:\n", data)

print("Mean:", data.mean())
print("Std Dev:", data.std())
print("Min:", data.min())
print("Max:", data.max())
print("Sum:", data.sum())

Array:
 [[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]
Mean: 0.2959553058837369
Std Dev: 0.7125565880862972
Min: -0.4694743859349521
Max: 1.5792128155073915
Sum: 3.5514636706048432


## 📊 Axis-Based Computation

In [233]:
data = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Column-wise (axis=0)
print("Sum (axis=0):", data.sum(axis=0))

# Row-wise (axis=1)
print("Sum (axis=1):", data.sum(axis=1))

Sum (axis=0): [5 7 9]
Sum (axis=1): [ 6 15]


### 🔍 Axis Rule:

- axis = 0 → operate DOWN (column-wise)
- axis = 1 → operate ACROSS (row-wise)

👉 This is one of the most asked interview concepts

## 🔍 Boolean Vectorization

In [234]:
arr = np.array([1, 5, 10, 15])

print(arr > 5)
print((arr > 5).sum())
print((arr > 5).any())
print((arr > 5).all())

[False False  True  True]
2
True
False


### 🔍 Meaning:
- sum() → count True values
- any() → at least one True
- all() → all True

👉 Useful for filtering and conditions

## 📐 Euclidean Distance Between Two Vectors

In [235]:
vec1 = np.random.randn(5)
vec2 = np.random.randn(5)

distance = np.sqrt(np.sum((vec1 - vec2) ** 2))

print("Distance:", distance)

Distance: 2.417741427344559


### 🔍 Formula:
distance = √ Σ (x1 - x2)^2

👉 Used in:
- Machine Learning
- Clustering
- Similarity detection

## ⚠️ Vectorization vs Loops

In [236]:
# Slow way (loop)
result = []
for i in arr:
    result.append(i * 2)

# Fast way (vectorized)
result = arr * 2

### 🚀 Key Takeaway:
Vectorization = Speed + Clean Code + Efficiency

👉 Always prefer NumPy operations over loops

## 🔥 Broadcasting in NumPy

Broadcasting allows NumPy to perform operations on arrays of **different shapes**.

👉 Instead of copying data, NumPy **virtually stretches** smaller arrays.

### Why it matters:
- Eliminates loops
- Saves memory
- Enables fast computations

## 🧪 Example 1: Adding Scalar to Array

In [237]:
import numpy as np

arr = np.array([1, 2, 3])

print(arr + 5)

[6 7 8]


### 🔍 Insight:
Scalar `5` is automatically applied to every element

👉 Internally: [5,5,5]

## 🧪 Example 2: Row + Column

In [238]:
a = np.array([[0, 0, 0],
              [10, 10, 10],
              [20, 20, 20]])

b = np.array([1, 2, 3])

print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]]


### 🔍 What happens?

b = [1, 2, 3]

becomes:

[[1, 2, 3],
 [1, 2, 3],
 [1, 2, 3]]

👉 Then added row-wise

## 📏 Broadcasting Rules

NumPy compares shapes from **right to left**

Rule 1: Dimensions must be equal  
Rule 2: OR one of them must be 1  
Rule 3: Otherwise → ERROR

a = np.ones((3, 3))
b = np.array([1, 2, 3])

print(a + b)   # Works

In [239]:
a = np.ones((3, 3))
b = np.array([1, 2, 3]) # Changed to 3 elements to match the last dimension of 'a'

print(a + b)   # Works now

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


Shapes (3,3) and (2,) → not compatible

👉 Broadcasting fails

## 🧪 Example 3: Column Broadcasting

In [240]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

mean = a.mean(axis=0)

print("Mean:", mean)
print("Centered Data:\n", a - mean)

Mean: [2.5 3.5 4.5]
Centered Data:
 [[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


### 🔍 What happens?

mean = [2.5, 3.5, 4.5]

is stretched to:

[[2.5, 3.5, 4.5],
 [2.5, 3.5, 4.5]]

👉 Then subtraction happens

## 🧪 Example 4: Normalization

In [241]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

normalized = (a - a.mean(axis=0)) / a.std(axis=0)

print(normalized)

[[-1. -1. -1.]
 [ 1.  1.  1.]]


### 🔍 Used in:
- Machine Learning preprocessing
- Feature scaling
- Data normalization

## 🎯 Final Summary

Broadcasting = automatic shape alignment

👉 No loops
👉 No copies
👉 Super fast

## 🎲 Random Number Generation in NumPy

Random number generation is widely used in:
- Simulations
- Machine Learning
- Testing and sampling

## 🧪 Generating Random Numbers

In [242]:
import numpy as np

# Uniform distribution [0,1)
print(np.random.rand(2, 3))

# Normal distribution (mean=0, std=1)
print(np.random.randn(5))

# Random integers
print(np.random.randint(0, 10, 5))

[[0.19967378 0.51423444 0.59241457]
 [0.04645041 0.60754485 0.17052412]]
[-0.60063869 -0.29169375 -0.60170661  1.85227818 -0.01349722]
[2 0 3 1 7]


### 🔍 Insight:
- rand() → uniform distribution
- randn() → normal distribution
- randint() → discrete values

## 🎯 Setting Random Seed

In [243]:
np.random.seed(42)

print(np.random.rand(3))
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]
[0.59865848 0.15601864 0.15599452]


### 🔍 Why use seed?

👉 Ensures same output every time  
👉 Important for experiments & debugging

### 🔍 Why use seed?

👉 Ensures same output every time  
👉 Important for experiments & debugging

In [244]:
# Simulate student scores
scores = np.random.randint(40, 100, 20)

print("Scores:", scores)

print("Mean:", scores.mean())
print("Max:", scores.max())
print("Min:", scores.min())

Scores: [50 50 63 92 75 79 63 42 61 92 41 63 83 69 77 41 99 60 72 51]
Mean: 66.15
Max: 99
Min: 41


### 🔍 Real-world use:
- Data simulation
- Testing algorithms
- Performance evaluation

## 🧠 Final Summary of NumPy Concepts

In this assignment, we explored:

### 🔹 Array Creation
- 1D, 2D arrays from lists
- Special arrays (zeros, ones, linspace)

### 🔹 Array Properties
- dtype, shape, ndim, size

### 🔹 Reshaping
- reshape(), flatten(), ravel()

### 🔹 Indexing & Slicing
- Basic indexing
- Fancy indexing
- Boolean masking

### 🔹 Memory Model
- Row-major storage (C-style)

### 🔹 Vectorization
- Element-wise operations
- Faster than loops

### 🔹 Broadcasting
- Operations on different shapes
- Automatic expansion

### 🔹 Random Numbers
- rand(), randn(), randint()
- Reproducibility using seed

## 💡 Key Learnings

- NumPy enables efficient numerical computation
- Vectorization eliminates the need for loops
- Broadcasting simplifies complex operations
- Proper understanding of indexing is critical for data manipulation

👉 These concepts are foundational for:
- Data Science
- Machine Learning
- Deep Learning